### PR TITLE
Migrate to CircleCI

### PR DESCRIPTION
**Pull request by freak4pc**
Supersedes #25

### CODE REVIEW

**Comment by freak4pc** [comment]
Ok, this looks great so far.
There are two last things to do - Update the CI badge, and see if it’s possible to cache Carthage build a bit better. When this is ready I’ll remove the WIP badge. 

Regarding slack integration, it’s done from theDasjboard itself, not in the yml file, so that should be done later after this is merged in.

**Comment by kzaher** [comment]
@freak4pc matrix builds run in parallel, but we can start with this.

**Comment by freak4pc** [comment]
@kzaher Let me give this a quick try with V2, it doesn't seem too tricky. I'll have a separate commit, and we can revert if any issues.

**Comment by freak4pc** [comment]
@kzaher Ok so - V2 will give you this "parallelism", but thing is - you don't get parallel builds in OSS anyways, so I'm not sure if we are gaining anything from working with this. 

Still don't mind having the tests separated like down here (once I fix the problematic ones), but they will still run in Serial and not in Parallel unless CircleCI will be willing to add more containers for free somehow (which seems unlikely).

**Comment by freak4pc** [comment]
Another issue: 
Your builds never ran in Matrix. For example your Cocoapods tests seem to "count on the fact" the submodules installed first (otherwise you have to add RxTest and RxBlocking to the test target in the Podfile)

Second issue, the Xcode project has the "Carthage" build step in it for Cocoapods as well, which seems to cause some issues when trying to build separately for some strange user. Need to dig into it a bit deeper if we want to use v2 here.

**Comment by freak4pc** [comment]
If you want the "separate workflows" solution, I think the best way to "sort this out" is to reimagine what we're testing here. 
Right now you're testing a project is able to build and test vs both Carthage, Cocoapods, Submodules and SPM. 

What I think might be better to do is 

- Submodules - just checkout and do a Test and Build, those are quick so no harm 
- Carthage: Do a regular Carthage build on both tvOS and iOS without Xcode at all - if those succeed, Carthage is fine. I don't see a reason necessarily to build against the sample project. This would also mean you can remove the build phase script in this case. 
- Cocoapods: We can either build vs. the example project or just do a full `pod spec lint` which makes a "Fake" Xcode project to test the Cocoapod installs successfully
- SPM - As today `swift build` and `swift test` are relatively quick and performant

The two sticky points are Carthage and CocoPods **together**. So I think my point is, instead of trying to build and test vs. an example project for all of these platform, try to only build the framework itself for each of the platforms and only do the tests for one point (for example the Submodules option)

**Comment by freak4pc** [comment]
After our discussion this has been reverted to the standard style v1 config. Ready for you whenever @kzaher

**Comment by freak4pc** [comment]
cc @Vkt0r

**Comment by freak4pc** [comment]
@kzaher This doesn't really seem like a matrix build doesn't entirely ensure parallelism, sometimes it would run sequentially just because you get it out of the box. 

The main way you can see this is true is since your project worked with Cocoapods even though your Podfile doesn't include RxTest and RxBlocking (while your test target uses it), probably since the submodules kick in, in that case. 

When I tired an entirely separated parallel build it didn't work well and failed because of the Carthage build step (it tries to copy the frameworks and couldn't find them, it might find it in your since it's cached in Travis, but not sure)

carthage deintegrate would also mean get rid of the build step in this case, the folder itself actually has no meaning in the build process besides the fact the static frameworks are sitting there

In any case, since CircleCI don't give parallel builds here, and as we discussed in private, I don't think it matters that much in our case, unless you have any notes. 

I don't mind removing a git reset instead of a pod reintegrate if its nicer for you.

**Comment by kzaher** [comment]
> @kzaher This doesn't really seem like a matrix build, doesn't seem like it entirely ensure parallelism, sometimes it would run sequentially just because you get it out of the box.

You mean to say that it's potentially parallel, but could be serial depending on available workers?

> The main way you can see this is true is since your project worked with Cocoapods even though your Podfile doesn't include RxTest and RxBlocking (while your test target uses it), probably since the submodules kick in, in that case.

Ok, I've managed to reproduce that. We were indeed missing:
```
@@ -9,6 +9,8 @@ end
 target 'RxFeedbackTests' do
   pod 'RxSwift', '~> 4.0'
   pod 'RxCocoa', '~> 4.0'
+  pod 'RxTest', '~> 4.0'
+  pod 'RxBlocking', '~> 4.0'
 end
```

I have no idea why it built before. If we added this, CocoaPods should work.

> When I tried an entirely separated parallel build it didn't work well and failed because of the Carthage build step (it tries to copy the frameworks and couldn't find them, it might find it in your current set-up since it's cached in Travis, but not sure)

I've missed RxSwift submodule, and that was causing my successful builds. Copy frameworks could be changed with a script that looks for them in product directory or Carthage directory.

> carthage deintegrate would also mean get rid of the build step in this case, the folder itself actually has no meaning in the build process besides the fact the static frameworks are sitting there

I'm not sure what do you mean by this. Can you explain the exact problem?

> I don't mind removing a git reset instead of a pod reintegrate if its nicer for you.

I think we should use `git reset HEAD --hard; git clean -d -f; git rm -rf RxSwift`.

**Comment by freak4pc** [comment]
I already did this (fixing the Podfile), and it didn't resolve the problem. Let me push the v2 script here real quick and you'll see the issue I was having. I'm 99% sure its relates to the build phase.

**Comment by kzaher** [comment]
I believe this is also an important part.

> Copy frameworks could be changed with a script that looks for them in product directory or Carthage directory.

**Comment by freak4pc** [comment]
Here, @kzaher - Feel free to track these 4 builds. 

Regarding the carthage thing, Indeed it is - but It's not straight forward. It's not a "Run Script Phase" , the frameworks are "linked as binary" to the project, and they don't exist, so it fails (there is also some Header phase where it doesn't exist). 

627a06aa-db9e-4162-a7b5-3afa6ae85cb3

Maybe setting them to Optional would work but I'd have to try that separately. 

You'll see these warnings when the builds do their thing.

**Comment by freak4pc** [comment]
@kzaher check out the failures: 

for CocoaPods: 
```
The following build commands failed:
	PBXCp /Users/distiller/Library/Developer/Xcode/DerivedData/RxFeedback-bnjsoiilaqkzbpfawauivabgwgxp/Build/Products/Debug-iphonesimulator/RxCocoa.framework /Users/distiller/Library/Developer/Xcode/DerivedData/RxFeedback-bnjsoiilaqkzbpfawauivabgwgxp/Build/Products/Debug-iphonesimulator/Example.app/Frameworks/RxCocoa.framework
	PBXCp /Users/distiller/Library/Developer/Xcode/DerivedData/RxFeedback-bnjsoiilaqkzbpfawauivabgwgxp/Build/Products/Debug-iphonesimulator/RxSwift.framework /Users/distiller/Library/Developer/Xcode/DerivedData/RxFeedback-bnjsoiilaqkzbpfawauivabgwgxp/Build/Products/Debug-iphonesimulator/Example.app/Frameworks/RxSwift.framework
```

For Carthage the error is a bit unclear, but we can debug that separately.

**Comment by Vkt0r** [comment]
@freak4pc @kzaher quick update Definitely setting the status of the frameworks as `Optional` and isolating the `carthage` step didn't make any difference in the failure of the step. I was able to extract the xcodebuild-log from `carthage` using the Artifacts in CircleCI. This is the failure in the step `Carthage Build tvOS`:

```bash
/Users/distiller/project/Sources/RxFeedback/Feedbacks.swift:9:8: error: module file was created for incompatible target arm64-apple-ios8.0: /Users/distiller/project/Carthage/Build/iOS/RxSwift.framework/Modules/RxSwift.swiftmodule/arm64.swiftmodule
import RxSwift
       ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

So pretty much Xcode is using an incorrect framework here as is trying to use the iOS version. Continue working on it

**Comment by freak4pc** [comment]
I'm withdrawing from this effort for now. Seems that for concurrent builds Travis works better. This PR and branch still lives if anyone else would want to take an attempt on it.

**Pull request closed without merging**
