### PR TITLE
[Proposal] Empower Reducer with State Monad

### PR DESCRIPTION
**Pull request by orakaro**
Hello guys, I have been thinking of improving the `reduce` function in case there is complexity in transition rules. Until now we have to write full length `switch` lines. 

If there are multiple rules for same event then `reduce` can be even harder to read:
```swift
func reduce(state: State, event: Event) -> State {
    switch event {
    case .event1: 
        switch state {
        case .state1: // ...
        case .state2: // ...
        // every other cases ...
        }
    }
    // every other cases ...
}
```

This PR attempts to provide a more flexible and readable way to define these kind of graphs. Basically the type of reduce `(S, E) -> S` can be rewritten as `(E) -> (S) -> S` or `(E) -> StateMonad[S]`. `Reducer` instance will accept each individual rule and later combines them all to produce a final lambda.

```swift
let reducer = Reducer<State, Event>()
reducer.accept(.event1) { state in // Modify current state and return new state }
reducer.accept(.event2) { state in //... }
reducer.accept(.event3) { state in //... }
```

This idea comes from my talk about [Monadic Automaton](https://speakerdeck.com/dtvd/mercari-atte-and-automaton).

### CODE REVIEW

**Comment by freak4pc** [comment]
Really interested in how this PR will turn our as the idea is fascinating. I also really enjoyed your slides, looking forward to toying with this :)

**Comment by kzaher** [comment]
Hi @orakaro ,

thnx for this PR.

> Hello guys, I have been thinking of improving the reduce function in case there is complexity in transition rules.

There are many ways how one would want to write the reducer, some are more sophisticated, some are more straightforward.

For some reason I really have a hard time explaining this concept to people even on small reducers that just work on small number of events and small state.

I would rather leave the choice how to write big reducer to advanced users who already probably have their own approaches, then add them here where there would probably additionally confuse beginners.

I hope that makes sense.

**Comment by orakaro** [comment]
I had the same concern before implementing. But I think this only adds an additional complexity in _library implement_, but not _library usage_ .

This is just additional `system` method and users still have their choice to use "regular" method like before. Actually if they don't have to read the detail implement of RxFeedback the usage is pretty straightforward as you can see on `Counter` example
```swift
let reducer = Reducer<State, Event>()
reducer.accept(event: .increment) { $0 + 1 }
reducer.accept(event: .decrement) { $0 - 1 }

// instead of
reduce: { (state, event) -> State in
    switch event {
    case .increment:
        return state + 1
    case .decrement:
        return state - 1
    }
}
```

And this help advanced users with complex reducer also, so I think it is no harm to be a part of RxFeedback.

**Comment by freak4pc** [comment]
I also like this approach because it lets you "split" the reducer implementations instead of having them all in one place (which you're forced to do in an exhaustive switch). 

If you have a very long stay machine you could easily split the "setup" into multiple methods / logical points etc. 

Also +1 for redability in this sense... 

This is all Kruno's decision but I think, since this is purely additive and doesn't break existing behavior or API contract, I'm really for this.

**Comment by sergdort** [comment]
Hi, guys! I agree with @kzaher :) 
Especially taking into account the conversation from slack where @fpillet pointed out that to make it work with `enum`s that have associated values we will need to conform to the `Hashable`. 

I also wonder does it mean that I need to have an associated value beforehand to something like:

`reducer.accept(loaded(something)) { ... }`

**Comment by DanielAsher** [comment]
I think the transition table is the least attractive part of most `system` implementations I've seen. @orakaro, I really like your attempt to improve the coding of `reduce`. Unfortunately - and this also applies to the DSL in `RxAutomaton`, as soon as you add associated values to your event enum, the solution breaks down. For those reasons I would agree with @kzaher.

Ideally there would be examples of using Behavior Trees, which avoids the (quickly ridiculous) switchboard at the heart of a `system`. Has anyone tried waiting for parallel effects in an FSM? It's a combinatorial nightmare - yet trivial within Rx and BTs.

**Comment by freak4pc** [comment]
> as soon as you add associated values to your event enum, the solution breaks down

> enums that have associated values we will need to conform to the Hashable.

Wouldn't this be solved in Swift 4.1 with Conditional Conformance ?

**Comment by DanielAsher** [comment]
> I also wonder does it mean that I need to have an associated value beforehand to do something like:
>     `reducer.accept(.loaded(something)) { ... }`

@sergdort @orakaro :  I think this is the crux of the matter. Without allowing for destructuring of the event payload you box yourself in to events that only act as labels. Ideally you would want something like:

`reducer.acceptOnLoaded { something in ... }` or
`reducer.onLocationUpdate { user, location, time in ... }`

This is probably possible to generate at compile time with [Sourcery](https://github.com/krzysztofzablocki/Sourcery).

**Pull request closed without merging**
