### PR TITLE
Carthage CircleCI step

### PR DESCRIPTION
**Pull request by Vkt0r**
Substep Carthage step for #26

### CODE REVIEW

**Comment by freak4pc** [comment]
@Vkt0r Could you try moving the tvOS build after the Xcode phase? 

meaning
- Build iOS
- Build Xcode
- Build tvOS

**Comment by freak4pc** [comment]
@Vkt0r I would move the xcodebuild in between them like I mentioned up here ^

Also it might be beneficial to remove the Carthage folder before building iOS

**Comment by Vkt0r** [comment]
@freak4pc Exactly what I'm doing now in the last commit

**Comment by freak4pc** [comment]
@Vkt0r Not exactly - you do iOS, tvOS, Xcode

What I'm saying is 

- Build iOS
- Build Xcode
- eventually, build tvOS - after the Xcode build is already good

**Comment by Vkt0r** [comment]
Uhmm got, let's try it.

**Comment by Vkt0r** [comment]
@freak4pc Now we move at least one step forward, `Carthage Build iOS` finished without errors at least. Now `Build iOS` is the one failing with the framework reference

**Comment by freak4pc** [comment]
Good idea trying to set the frameworks back to required - i did it as an attempt to fix it 🙄

**Comment by Vkt0r** [comment]
@freak4pc Unfortunately it didn't work it continues without linking the `RxSwift.framework` when the build phase is running.

**Comment by freak4pc** [comment]
I'm not entirely sure the linking is the issue ...

**Comment by freak4pc** [comment]
See #26

**Pull request closed without merging**
